name: 'Dispatch merged PR notification'

# Ensures that only one workflow is run per branch at a time.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

on:
  push:
    branches:
      - master
      - release-[0-9]+.[0-9]+

permissions: {}

jobs:
  dispatch-merged-pr-notififcation:
    name: Dispatch merged PR notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.NOTIFY_BOT_PAT_TOKEN }}
          script: |
            return github.rest.repos.createDispatchEvent({
              owner: '${{ vars.NOTIFY_REPO_OWNER }}',
              repo: '${{ vars.NOTIFY_REPO_NAME }}',
              event_type: '${{ vars.NOTIFY_EVENT_TYPE }}',
              client_payload: {
                branch: context.payload.pull_request.base.ref,
              },
            })
