name: 'Sync kumahq/kuma-gui with kumahq/kuma'

# Ensures that only one workflow is run per branch at a time.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

on:
  # Uncomment the following pull_request event to test this workflow in a PR
  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize

  workflow_dispatch: {}

permissions:
  contents: read # for checking out the repository (e.g. actions/checkout)
  pull-requests: write # for reading, and creating pull requests (via peter-evans/create-pull-request)

jobs:
  bump:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/bootstrap/
        with:
          install-cmd: |
            make install
      - run: |
          make bump
      # For testing only hence only on a PR event
      - if: ${{ github.event_name == 'pull_request' }}
        run: |
          git ls-files --exclude-standard --modified --deleted --others -t
          echo 'chore(deps): sync kumahq/kuma-gui with kumahq/kuma'
          echo '=========='
          ls -al ./active-branches.json

      - name: Generate GitHub app token
        # Not during testing only hence not on a PR event
        if: ${{ github.event_name != 'pull_request' }}
        id: github-app-token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      # https://github.com/peter-evans/create-pull-request
      - uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        # Not during testing only hence not on a PR event
        if: ${{ github.event_name != 'pull_request' }}
        with:
          token: ${{ steps.github-app-token.outputs.token }}
          commit-message: 'chore(deps): sync kumahq/kuma-gui with kumahq/kuma'
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          signoff: true
          branch: chore/sync-kumahq-kuma
          delete-branch: true
          title: 'chore(deps): sync kumahq/kuma-gui with kumahq/kuma'
          body: |
            Sync `kumahq/kuma-gui` with `kumahq/kuma`

            Please ensure you also do the following manual tasks:

            - [ ] Perform any post-release renovate tasks such as lock file maintenance, major node upgrades via the [Dependency Dashboard](https://github.com/kumahq/kuma-gui/issues/3921)

            Triggered by [action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          draft: false
