name: Sync Kuma OAS

# Ensures that only one workflow is run per branch at a time.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

on:
  # Uncomment the following pull_request event to test this workflow in a PR
  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
        description: The base branch for which to create a PR
  repository_dispatch:
    types:
      - SYNC_KUMA_OAS

permissions:
  contents: read # for checking out the repository (e.g. actions/checkout)
  pull-requests: write # for reading, and creating pull requests (via peter-evans/create-pull-request)

env:
  BRANCH: ${{ github.event.client_payload.branch || inputs.branch || github.base_ref }}

jobs:
  sync:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - name: "@kumahq/kuma-http-api"
            path: packages/kuma-http-api
            source: kumahq/kuma
    name: |
      Updating ${{ matrix.package.name }} from ${{ matrix.package.source }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/bootstrap/
        with:
          install-cmd: |
            make install
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ matrix.package.source }}
          ref: ${{ env.BRANCH }}
          path: ${{ matrix.package.path }}/kuma
      - run: |
          make -C ${{ matrix.package.path }} build \
            GIT_SHA=$(git -C ${{ matrix.package.path }}/kuma rev-parse HEAD)
          echo KUMA_HEAD="$(git -C ${{ matrix.package.path }}/kuma rev-parse --short HEAD)" >> "$GITHUB_ENV"
      - if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo 'chore(kuma-http-api): bump kuma OAS based types - ${{ env.KUMA_HEAD }}'
          echo '=========='
          echo 'Files changed:'
          git ls-files --exclude-standard --modified --deleted --others -t
          echo '=========='
          echo 'Diff:'
          git -C packages/kuma-http-api --no-pager diff --unified=0
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        if: ${{ github.event_name != 'pull_request' }}
        id: github-app-token
        with:
          # no owner and no repositories as we only want access to this repository
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          token: ${{ steps.github-app-token.outputs.token }}
          base: ${{ env.BRANCH }}
          commit-message: |
            chore(kuma-http-api): bump kuma OAS based types - ${{ env.KUMA_HEAD }}

            Generates the OAS based types from the latest kuma OAS (${{ env.KUMA_HEAD }}).
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          team-reviewers: kuma-gui-maintainers
          signoff: true
          branch: chore/update-kuma-http-api-types-in-${{ env.BRANCH }}
          delete-branch: true
          title: 'chore(kuma-http-api): bump kuma OAS based types - ${{ env.KUMA_HEAD }}'
          body: |
            Generates the OAS based types from the latest kuma OAS.

            > Changelog: chore(deps): use latest OAS from kuma - ${{ env.KUMA_HEAD }}
          draft: false
